name: CI Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # 1. Backend Linting (Ruff)
  backend-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.10"
      - name: Install Ruff
        run: pip install ruff==0.14.14
      - name: Run Ruff Check
        run: ruff check api-constantec/

  # 2. Backend Formatting (Ruff)
  backend-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.10"
      - name: Install Ruff
        run: pip install ruff==0.14.14
      - name: Run Ruff Format
        run: ruff format --check api-constantec/

  # 3. Frontend Linting (ESLint)
  frontend-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: constantec-web-app
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.16.0"
          cache: 'npm'
          cache-dependency-path: constantec-web-app/package-lock.json
      - run: npm install
      - run: npm run lint

  # 4. Frontend Formatting (Prettier)
  frontend-format:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: constantec-web-app
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.16.0"
      - run: npm install
      - run: npx prettier --check .